### ISSUE TITLE
Is there a way to use Blaze HTML instead of Mustache templates?

### ISSUE THREAD

**Issue by JonathanReeve** [ChrisPenner/SitePipe#14]
It'd be nice to write HTML using blaze instead of writing it out the long way. Is there a way to do that using SitePipe?

**Comment by ProofOfPizza** [comment]
You can use blaze to generate the moustache/HTML templates. See [gitlab](https://gitlab.com/AntiforZ.com/templating)

**Comment by ChrisPenner** [comment]
SitePipe uses simple Aeson values for everything, so you should be able to write your own resource renderer that writes Blaze html to a file, otherwise please check out [Slick](https://github.com/ChrisPenner/Slick), it's a successor to SitePipe which is based on Shake, which is much more adaptable and should allow you to write whichever files you like :)
