### ISSUE TITLE
Consider using Shake

### ISSUE THREAD

**Issue by bandali** [ChrisPenner/SitePipe#15]
Consider using [Shake](http://shakebuild.com/) for generation, cleanup, and caching. Also see @emilaxelsson's [Milkshake](https://github.com/emilaxelsson/milkshake) example.

**Comment by ChrisPenner** [comment]
I've looked into this actually; it's doable of course, but quite tricky due to the nature of how assets are currently loaded; and the fact that users may choose to do things dynamically in between loading an asset and rendering it which may not properly be reflected in the caching.

It'd be a 'nice-to-have' but I believe most sites using SitePipe are small enough to rebuild entirely.

It was quite a while that I took a look at it, but I did write up a preliminary branch for it. I'm not sure where it was at when I abandoned it, but you're welcome to take a look and see if you can find a way to do it where I couldn't; the branch is here: https://github.com/ChrisPenner/SitePipe/tree/shake

Feel free to re-open if you have any insights into it, or make a pull request if you can get something working, but as is I don't see it happening any time soon 😢

**Comment by ChrisPenner** [comment]
@aminb Assuming you've seen this already; but I finally got around to building a site-generator with Shake; check out [Slick](https://github.com/chrispenner/slick)!

**Comment by bandali** [comment]
@ChrisPenner I've definitely seen Slick, and I think it lives up to its name :)
