### ISSUE TITLE
SitePipe ignores pandoc metadata

### ISSUE THREAD

**Issue by isovector** [ChrisPenner/SitePipe#17]
SitePipe's loading machinery attempts to parse all files as YAML in an attempt to extract their metadata. This is clearly the wrong approach when using a pandoc reader, as pandoc [manages its own metadata](https://www.stackage.org/haddock/lts-9.0/pandoc-types-1.17.0.5/src/Text.Pandoc.Definition.html#Meta). 

The obvious solution to this would be to change the reader type to be `String -> IO (Value, String)`, use the existing YAML parsing machinery for `markdownReader`, and then extract pandoc's `Meta` for `mkPandocReader`.

I'm willing to submit a PR for this if you're happy with the approach; if not, do you have any suggestions for how to continue without my needing to rebuild all of the loading machinery?

**Comment by ChrisPenner** [comment]
If you can whip up a suitable patch I'd be glad to accept it!

Otherwise, definitely check out [Slick](https://github.com/ChrisPenner/Slick); it's a successor to SitePipe and supports loading meta directly from the Pandoc reader using Pandoc 2.0

It will require re-writing your site builder using Shake, but IMHO that's worth it just for the speed improvement and caching.
